// -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        The WPF ShaderEffect Generator
//        http://wpfshadergenerator.codeplex.com
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace UIControls.Effects
{
    using System;
    using System.Windows;
    using System.Windows.Media;
    using System.Windows.Media.Effects;
    using System.Windows.Media.Media3D;
    
    
    /// <summary>A HSV Color Quad shader for WPF.</summary>
    public class ColorRangeQuad : System.Windows.Media.Effects.ShaderEffect
    {
        
        /// <summary>The range input.</summary>
        public static readonly DependencyProperty InputColorProperty = DependencyProperty.Register("InputColor", typeof(System.Windows.Media.Color), typeof(ColorRangeQuad), new UIPropertyMetadata(Color.FromArgb(255,0,0,0), PixelShaderConstantCallback(0)));
        /// <summary>The color input.</summary>
        public static readonly DependencyProperty RangeProperty = DependencyProperty.Register("Range", typeof(System.Single), typeof(ColorRangeQuad), new UIPropertyMetadata((float)0, PixelShaderConstantCallback(1)));
        /// <summary>The implicit input sampler passed into the pixel shader by WPF.</summary>
        public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(ColorRangeQuad), 0, SamplingMode.Auto);
        
        public ColorRangeQuad()
        {
            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri("pack://application:,,,/UIControls;component/Effects/ColorRangeQuad.ps", UriKind.Absolute);
            this.PixelShader = pixelShader;
            this.UpdateShaderValue(InputColorProperty);
            this.UpdateShaderValue(RangeProperty);
            this.UpdateShaderValue(InputProperty);
            this.DdxUvDdyUvRegisterIndex = -1;
        }
        
        /// <summary>The range input.</summary>
        public virtual System.Windows.Media.Color InputColor
        {
            get
            {
                return ((System.Windows.Media.Color)(this.GetValue(InputColorProperty)));
            }
            set
            {
                this.SetValue(InputColorProperty, value);
            }
        }
        
        /// <summary>The color input.</summary>
        public virtual float Range
        {
            get
            {
                return ((float)(this.GetValue(RangeProperty)));
            }
            set
            {
                this.SetValue(RangeProperty, value);
            }
        }
        
        /// <summary>The implicit input sampler passed into the pixel shader by WPF.</summary>
        public virtual System.Windows.Media.Brush Input
        {
            get
            {
                return ((System.Windows.Media.Brush)(this.GetValue(InputProperty)));
            }
            set
            {
                this.SetValue(InputProperty, value);
            }
        }
    }
}
