// -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        The WPF ShaderEffect Generator
//        http://wpfshadergenerator.codeplex.com
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace UIControls.Effects
{
    using System;
    using System.Windows;
    using System.Windows.Media;
    using System.Windows.Media.Effects;
    using System.Windows.Media.Media3D;
    
    
    /// <summary>A HSV Color Rectagle shader for WPF.</summary>
    public class HSVRectangle : System.Windows.Media.Effects.ShaderEffect
    {
        
        /// <summary>The luminance offset.</summary>
        public static readonly DependencyProperty LuminanceProperty = DependencyProperty.Register("Luminance", typeof(System.Single), typeof(HSVRectangle), new UIPropertyMetadata((float)1, PixelShaderConstantCallback(0)));
        /// <summary>The Target Hue to be displayed in center. 0 - 1</summary>
        public static readonly DependencyProperty HueProperty = DependencyProperty.Register("Hue", typeof(System.Single), typeof(HSVRectangle), new UIPropertyMetadata((float)0.5, PixelShaderConstantCallback(1)));
        /// <summary>The range to be displayed. 0 is single color, 1 is whole range</summary>
        public static readonly DependencyProperty RangeProperty = DependencyProperty.Register("Range", typeof(System.Single), typeof(HSVRectangle), new UIPropertyMetadata((float)1, PixelShaderConstantCallback(2)));
        /// <summary>The implicit input sampler passed into the pixel shader by WPF.</summary>
        public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(HSVRectangle), 0, SamplingMode.Auto);
        
        public HSVRectangle()
        {
            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri("pack://application:,,,/UIControls;component/Effects/HSVRectangle.ps", UriKind.Absolute);
            this.PixelShader = pixelShader;
            this.UpdateShaderValue(LuminanceProperty);
            this.UpdateShaderValue(HueProperty);
            this.UpdateShaderValue(RangeProperty);
            this.UpdateShaderValue(InputProperty);
            this.DdxUvDdyUvRegisterIndex = -1;
        }
        
        /// <summary>The luminance offset.</summary>
        public virtual float Luminance
        {
            get
            {
                return ((float)(this.GetValue(LuminanceProperty)));
            }
            set
            {
                this.SetValue(LuminanceProperty, value);
            }
        }
        
        /// <summary>The Target Hue to be displayed in center. 0 - 1</summary>
        public virtual float Hue
        {
            get
            {
                return ((float)(this.GetValue(HueProperty)));
            }
            set
            {
                this.SetValue(HueProperty, value);
            }
        }
        
        /// <summary>The range to be displayed. 0 is single color, 1 is whole range</summary>
        public virtual float Range
        {
            get
            {
                return ((float)(this.GetValue(RangeProperty)));
            }
            set
            {
                this.SetValue(RangeProperty, value);
            }
        }
        
        /// <summary>The implicit input sampler passed into the pixel shader by WPF.</summary>
        public virtual System.Windows.Media.Brush Input
        {
            get
            {
                return ((System.Windows.Media.Brush)(this.GetValue(InputProperty)));
            }
            set
            {
                this.SetValue(InputProperty, value);
            }
        }
    }
}
